export const ModalType = {
  // 로그인 / 회원가입
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_MAIL_SENT: "AUTH_MAIL_SENT",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",
  AUTH_SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",

  // 홈
  HOME_TERMS_AGREEMENT: "HOME_TERMS_AGREEMENT",
  HOME_TERMS_DETAIL: "HOME_TERMS_DETAIL",
  HOME_DOCTOR_OPINION: "HOME_DOCTOR_OPINION",
  HOME_TEMPORARY_MEASURE: "HOME_TEMPORARY_MEASURE",

  // 마이페이지
  MY_SYMPTOM_CHANGED: "MY_SYMPTOM_CHANGED",
  MY_SYMPTOM_NOT_SELECTED: "MY_SYMPTOM_NOT_SELECTED",
  MY_PROFILE_UPDATED: "MY_PROFILE_UPDATED",
  MY_WITHDRAW_NOTICE: "MY_WITHDRAW_NOTICE",
  MY_WITHDRAW_DONE: "MY_WITHDRAW_DONE",
} as const;

export type ModalType = (typeof ModalType)[keyof typeof ModalType];
